### ISSUE TITLE
[Feature] Contract CI/CD and checks

### ISSUE THREAD

**Issue by bitbeckers** [Network-Goods/hypercerts-protocol#57]
## Goal

Work on code quality and get automated feedback on contract state

## User stores

- [x] #58
- [x] #59
- [x] #60
- [x] As a developer, I want to publish a NPM package when creating a release with typed contracts (see: #50) 

## Resources:
- Gas report and test coverage via [Foundry](https://book.getfoundry.sh)
- [Slither in GitHub actions](https://github.com/gitcoinco/grants-round/blob/main/.github/workflows/contract.yml)

**Comment by brossetti1** [comment]
https://github.com/Network-Goods/hypercerts-protocol/pull/86 adding this as a reference for bullet point 2
