### ISSUE TITLE
[Architecture] Mandatory URIs?

### ISSUE THREAD

**Issue by bitbeckers** [Network-Goods/hypercerts-protocol#61]
it feels a little bit off to have `uri` a mandatory parameter here (even though it's practical for your usecase). From a code perspective, I as a consumer of this primitive would decide on my own whether I'd need token uris or e.g. generate metadata on chain (as you did before)

_Originally posted by @elmariachi111 in https://github.com/Network-Goods/hypercerts-protocol/pull/55#discussion_r1038291348_

**Comment by ryscheng** [comment]
In the interface we need to have some way to retrieve a URI

**Comment by bitbeckers** [comment]
#78
