### ISSUE TITLE
Overflow checks on TokenID

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts-protocol#80]
Since we're doing this masking technique to extract the TypeID from the TokenID, I think there's now a risk of an overflow on tokenID into TypeID, we can't just rely on built-in Solidity overflow checks.

See for example:
https://github.com/Network-Goods/hypercerts-protocol/blob/dev/src/SemiFungible1155.sol#L199

@bitbeckers can you verify if I am reading this correctly?

**Comment by bitbeckers** [comment]
I think so, yes. We should:
1) Write tests for these cases
2) Implement restrictions on minting params. 

It's a while ago, and the statement is incorrect, but I think there's a TODO here: https://github.com/Network-Goods/hypercerts-protocol/blob/dev/src/SemiFungible1155.sol#L45
