### ISSUE TITLE
Unable to reproduce contract ABI

### ISSUE THREAD

**Issue by jmoggr** [Network-Goods/hypercerts-protocol#89]
LOW PRIORITY

I am not sure how to create to the contract ABIs. None of the commands in the README created the 'abi' folder and I can't find anything specifically about producing the ABI in the foundry documentation (besides that it's supposed to be created during compilation, which didn't happen for me). 

I also tried compiling with `solc` and `solcjs` but was unable to get either to work with the remapping of the `lib` folder paths.

**Comment by bitbeckers** [comment]
You can run `yarn hardhat compile` which compiles the contracts and generates both and `abi` and `artifacts` folder. We use hardhat because of the OZ integration providing safety checks on UUPS upgrades.

**Comment by jmoggr** [comment]
That worked! Thanks, I'll update the README later today.
