### ISSUE TITLE
Release npm package

### ISSUE THREAD

**Issue by bitbeckers** [Network-Goods/hypercerts-protocol#9]
As a front-end dev, I want to have a typed contract packages so I can keep up to date with the latest changes in the Hypercert protocol contracts

- [ ] Protect main branch
- [ ] Release npm package
- [ ] Set up GitHub action for release on merge to main

**Comment by brossetti1** [comment]
@bitbeckers I opened an initial pr that sets up a package and publishing system. I left notes in the pr, feel free to take a look and let me know if this is at least in the direction you're looking for and we can sort it out here.
