### ISSUE TITLE
Unidentified contract on OpenSea

### ISSUE THREAD

**Issue by bitbeckers** [Network-Goods/hypercerts-protocol#92]
https://testnets.opensea.io/assets/goerli/0xffb1fbff7a40ea441aeae8036812af116f593995/17

<img width="352" alt="Screenshot 2023-01-25 at 12 44 43" src="https://user-images.githubusercontent.com/19667964/214555451-8ee2c06f-f118-41b6-a812-0a10fdfa7915.png">

**Comment by julienbrg** [comment]
[id #17](https://testnets.opensea.io/assets/goerli/0xffb1fbff7a40ea441aeae8036812af116f593995/17) displays correctly on OpenSea on my side (the link you provided), but not [id #2](https://testnets.opensea.io/assets/goerli/0xffb1fbff7a40ea441aeae8036812af116f593995/2).

**Comment by bitbeckers** [comment]
Ah yes, but that's a metadata issue. We focussing on the minting flow first and you can see that the quality of the data ("Properties" field) is way better. 

The issue is the reading of the contract name that OpenSea happily skips. I've added a screenshot to the original post

**Comment by julienbrg** [comment]
Thanks for your reply. 

https://stackoverflow.com/questions/68891144/how-to-fix-unidentified-contract-opensea-is-unable-to-understand-erc1155

It seems like OpenSea is still relying on some old implementation of ERC-1155…

Adding a `name` variable until OpenSea fixes that may be a solution.

**Comment by bitbeckers** [comment]
Non-issue, contract used was a seperate testing contract. HypercertMinter is represented as expected.

<img width="324" alt="Screenshot 2023-01-25 at 16 06 39" src="https://user-images.githubusercontent.com/19667964/214598911-c2437e76-478b-4c3e-950c-66f60f1e6f68.png">
